import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.css'
import CPUInspects from '@pages/cpu'
import GPUInspects from '@pages/gpu'
import MemoryInspects from './memory'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CPUInspects/>  
        <GPUInspects/>     
        <MemoryInspects />
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}

export default Home
